FROM node:20-alpine AS dev
WORKDIR /app
#install package
COPY package*.json ./
RUN npm install

#copy source code
COPY . .

# Start development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]