// Mock data for component categories
export const mockComponents = [
  {
    type: "Drive Motor",
    code: "MTR-001",
    total: 100,
    dueSoon: 12,
    replaced: 8,
    note: "Maxon EC45",
  },
  {
    type: "Battery Pack",
    code: "BAT-001",
    total: 100,
    dueSoon: 5,
    replaced: 15,
    note: "LiFePO4 48V",
  },
  {
    type: "Wheel Assembly",
    code: "WHL-001",
    total: 400,
    dueSoon: 23,
    replaced: 45,
    note: "Polyurethane",
  },
  {
    type: "LiDAR Sensor",
    code: "LDR-001",
    total: 100,
    dueSoon: 3,
    replaced: 2,
    note: "Sick TiM571",
  },
  {
    type: "Control Board",
    code: "CTL-001",
    total: 100,
    dueSoon: 0,
    replaced: 5,
    note: "Custom PCB v2.1",
  },
  {
    type: "Emergency Stop",
    code: "EMS-001",
    total: 100,
    dueSoon: 8,
    replaced: 12,
    note: "Schneider XB5",
  },
  {
    type: "Encoder",
    code: "ENC-001",
    total: 200,
    dueSoon: 15,
    replaced: 20,
    note: "Incremental 2048ppr",
  },
  {
    type: "Power Supply",
    code: "PSU-001",
    total: 100,
    dueSoon: 6,
    replaced: 10,
    note: "Mean Well 24V",
  },
  {
    type: "Camera Module",
    code: "CAM-001",
    total: 200,
    dueSoon: 4,
    replaced: 8,
    note: "Intel RealSense",
  },
  {
    type: "WiFi Module",
    code: "WIF-001",
    total: 100,
    dueSoon: 2,
    replaced: 3,
    note: "Industrial 5GHz",
  },
  {
    type: "Brake System",
    code: "BRK-001",
    total: 100,
    dueSoon: 18,
    replaced: 25,
    note: "Electromagnetic",
  },
  {
    type: "Cooling Fan",
    code: "FAN-001",
    total: 200,
    dueSoon: 10,
    replaced: 30,
    note: "12V DC 80mm",
  },
]

// Mock data for vehicle components
export const mockVehicleComponents = [
  {
    amrId: "AMR001",
    componentType: "Drive Motor",
    lastReplacement: "2024-03-15",
    daysRemaining: 245,
    status: "Tốt",
    note: "Hoạt động bình thường",
  },
  {
    amrId: "AMR002",
    componentType: "Drive Motor",
    lastReplacement: "2024-03-10",
    daysRemaining: 240,
    status: "Tốt",
    note: "",
  },
  {
    amrId: "AMR003",
    componentType: "Drive Motor",
    lastReplacement: "2023-12-20",
    daysRemaining: 160,
    status: "Tốt",
    note: "",
  },
  {
    amrId: "AMR004",
    componentType: "Drive Motor",
    lastReplacement: "2023-10-05",
    daysRemaining: 85,
    status: "Tốt",
    note: "",
  },
  {
    amrId: "AMR005",
    componentType: "Drive Motor",
    lastReplacement: "2023-08-15",
    daysRemaining: 34,
    status: "Sắp đến hạn",
    note: "Cần kiểm tra",
  },
  {
    amrId: "AMR006",
    componentType: "Drive Motor",
    lastReplacement: "2023-07-20",
    daysRemaining: 8,
    status: "Sắp đến hạn",
    note: "Lên lịch thay",
  },
  {
    amrId: "AMR007",
    componentType: "Drive Motor",
    lastReplacement: "2023-06-10",
    daysRemaining: -12,
    status: "Quá hạn",
    note: "Cần thay gấp",
  },
  {
    amrId: "AMR008",
    componentType: "Drive Motor",
    lastReplacement: "2024-01-15",
    daysRemaining: 195,
    status: "Tốt",
    note: "",
  },
  {
    amrId: "AMR009",
    componentType: "Drive Motor",
    lastReplacement: "2024-02-20",
    daysRemaining: 231,
    status: "Tốt",
    note: "",
  },
  {
    amrId: "AMR010",
    componentType: "Drive Motor",
    lastReplacement: "2023-11-05",
    daysRemaining: 125,
    status: "Tốt",
    note: "",
  },
]

// Mock data for component details
export const mockComponentDetails = [
  {
    amrId: "AMR002",
    partName: "Drive Motor",
    brand: "Maxon",
    model: "EC45",
    serviceLife: 365,
    installDate: "2024-03-10",
    nextMaintenance: "2025-03-10",
    status: "Tốt",
  },
  {
    amrId: "AMR005",
    partName: "Drive Motor",
    brand: "Maxon",
    model: "EC45",
    serviceLife: 365,
    installDate: "2023-08-15",
    nextMaintenance: "2024-08-15",
    status: "Sắp đến hạn",
  },
  {
    amrId: "AMR007",
    partName: "Drive Motor",
    brand: "Maxon",
    model: "EC45",
    serviceLife: 365,
    installDate: "2023-06-10",
    nextMaintenance: "2024-06-10",
    status: "Quá hạn",
  },
]

